# Generated by Django 3.1.7 on 2021-03-26 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0010_libro_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': ['nombre'], 'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
    ]
