# Generated by Django 3.1.7 on 2021-04-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0012_auto_20210405_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='isbn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ISBN'),
        ),
    ]
